#!/bin/bash

function removeBadge
{
    sed -i -e 's#</body></html>#<script>$(function(){ $("div").filter(function() { return $(this).css("background-color") == "rgb(43, 50, 57)"; }).hide(); });</script></body></html>#g' $1
}

# clone main site
wget --mirror -r --convert-links plainx-teaser.webflow.io
wget --mirror -r --convert-links plainx-teaser.webflow.io/the-team
cp plainx-teaser.webflow.io/* .
mv the-team team.html
removeBadge index.html
removeBadge team.html
rm -rf plainx-teaser.webflow.io

# clone faq and terms
rm -rf faq
wget --mirror -r --convert-links plainx-faq-tc.webflow.io
wget --mirror -r --convert-links plainx-faq-tc.webflow.io/terms
mv plainx-faq-tc.webflow.io faq
mv faq/terms terms/index.html
chmod -R 755 faq
removeBadge terms/index.html
removeBadge faq/index.html

# cleanup
find . -name "*-e" | xargs rm

# commit to git
git add .
git commit -m "update"
git push
